# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TransformersBaseTokenizer": "00_fastbert.ipynb",
         "SeqTokenizer": "00_fastbert.ipynb",
         "SeqTokenizeProcessor": "00_fastbert.ipynb",
         "segment": "00_fastbert.ipynb",
         "CustomTransformerModel": "00_fastbert.ipynb",
         "TransformersVocab": "00_fastbert.ipynb",
         "seed_all": "01_task3.ipynb",
         "loss_reweight": "01_task3.ipynb",
         "metrics": "01_task3.ipynb",
         "f1_score": "01_task3.ipynb",
         "F1Micro": "01_task3.ipynb"}

modules = ["fastbert.py",
           "model.py"]

doc_url = "https://PhilippMaxx.github.io/semeval2019_task3/"

git_url = "https://github.com/PhilippMaxx/semeval2019_task3/tree/master/"

def custom_doc_links(name): return None
